// @ts-check

// 此文件运行在 Node.js 环境 —— 请勿在此使用浏览器端代码（浏览器 API、JSX 等）

/**
 * 创建侧边栏可以让你：
 - 创建一组有序的文档
 - 为这组中的每篇文档渲染对应的侧边栏
 - 提供上一篇 / 下一篇的导航

 * 侧边栏既可以从文件系统自动生成，也可以在这里显式定义。

 * 想创建多少个侧边栏都可以。

 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 默认情况下，Docusaurus 会根据 docs 文件夹的目录结构自动生成侧边栏
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // 但你也可以手动创建一个侧边栏
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
